### ISSUE TITLE
Add University of Pittsburgh Center for Urban and Social Research to partners page

### ISSUE THREAD

**Issue by jobarratt** [frictionlessdata/website-old#73] opened 2016-08-19 14:55 UTC
@danfowler please review and add to the site. All info in the doc.

**Comment by danfowler** [comment] 2016-08-19 14:58
Different from https://github.com/frictionlessdata/frictionlessdata.io/issues/69 ?

**Comment by danfowler** [comment] 2016-08-25 20:31
Duplicate of #69

**Closed as completed by danfowler** 2016-08-25 20:31 UTC
Labels: enhancement
