### ISSUE TITLE
Improve theme

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/website-old#18] opened 2016-05-10 13:26 UTC
I'm booting this issue as an ongoing place to discuss some goals for v2 of the theme.
- [ ] Really nice styling for HTML tables for the inevitable multitude of simple examples of tabular data.
- [ ] There will be a fair amount of code examples, so it would be nice to have a really nice styling for code snippets.
---
suggestions from #10 (also see coments):
- [ ] Really concerned about "invisibility" of side menu and lack of top menu
  - For handbook this style made sense as more book like but we will need a more normal top menu here I think.
- [ ] bootstrap "boxes" stuff for e.g. /tools/ and some of /guides/ - see old http://data.okfn.org/tools/ for example
  - support fancy buttons

**Comment by pwalsh** [comment] 2017-06-15 07:31
Duplicate of https://github.com/frictionlessdata/frictionlessdata.io/issues/129

**Closed as completed by pwalsh** 2017-06-15 07:31 UTC
Labels: enhancement
