### ISSUE TITLE
[meta] Information Architecture and Overall Plan

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/website-old#2] opened 2016-04-28 09:00 UTC
Planning issue for describing the overall information architecture of Frictionless Data Site(s)

_Note: use "fd[.io]" as shorthand for "frictionlessdata[.io]_
# Sites and subsites
- `fd.io/`  - main site, most information lives here. Detailed description below.
- `specs.fd.io` - specifications site - see https://github.com/frictionlessdata/ideas/issues/242
- `profiles.fd.io` - profiles registry
- `tools.fd.io` ?? stuff like validate etc - may just have `validate.fd.io`

---
# fd.io

```
/
# all general documentation
# thought about putting this under other items but think we want to centralise
/doc/

/data-packages/
  # maybe /standards/ - summary and link elsewhere
  /specs/
  /profiles/

/tools/

# roadmap and developer stuff - maybe merge with community
/develop/

# community stuff
/community/

# get help ...
/help/

/about/
/blog/ -> labs (or blog.okfn.org one day)
```
## /
- Find out more
- Data Packages
- Tools
- Benefits
- Testimonials
- Get Started
- Get help
## /data-packages/
- publish
- find
- use
## /doc/

```
# index - want this to be good but maybe we can autogenerate ...
/

# guides to the specs
/data-package/
/tabular-data-package/
/geo-data-package/

# actually get started
/publish/
/publish/tabular/
/publish/geo/

# "patterns" and general howtos go here
/publish/faq/
/publish/faq/.../

# move these under /ref/ (for reference) ??
/csv/
/geojson/
```
## /data-packages/
- what are they - simple little diagram ...
- publish, find, use - sort of data.okfn.org front page
- mainly link elsewhere ...
## /tools/

Big box at top: "Have something to add: edit this page on github or submit an issue here."

Nice listing of tools. _Not_ a table but we do want a table of contents.

Structure options:
- Function (e.g. validate, model etc)
- Platform / language

Right now suggest we structure as follows:

```
## Top: Set of key functions with link to best tool

## By Function
  - items in here link to below

// might just drop this section and people can look in sections below

## Integrations

## Libraries

## Services
```
## /community/

Get involved, find people, develop the project

(other possible names: /contribute/ or /develop/)
- forum
- report issues
- chat channel
- twitter (labs)
- github (the organization) or perhaps github.com/frictionless
## /help/ (or maybe /support/)

Community Support -> forum

Paid Professional Support

Professional level training and support as well as custom development is available from Open Knowledge Services team. Please see http://services.okfn.org/
### /search/

/search/ - put a search box on site in navbar if possible (or sidebar)

Google custom search. Search this site, plus specs + labs blog (specific category ...?)
### /about/

About page. Partners etc.

**Comment by pwalsh** [comment] 2017-06-15 07:30
Duplicate of https://github.com/frictionlessdata/frictionlessdata.io/issues/129

**Closed as completed by pwalsh** 2017-06-15 07:30 UTC
Labels: enhancement
